# This is a GitHub Actions workflow file for Continuous Integration (CI)
name: CI # The name of the workflow

# The workflow will run on every push or pull request event
on: [push, pull_request]

jobs: # Define the jobs to run
  test: # This job is named "test"
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner

    steps: # The sequence of steps to execute in this job
      - uses: actions/checkout@v4
        # Step 1: Check out the repository code using the official checkout action

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
        # Step 2: Set up Python 3.10 on the runner using the official setup-python action

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
        # Step 3: Install dependencies
        # - Upgrade pip to the latest version
        # - Install the current project in editable mode with development dependencies

      - name: Lint (optional)
        run: |
          ruff --version || pip install ruff
          ruff check src tests
        # Step 4: Lint the code (optional)
        # - Check if ruff is installed, if not, install it
        # - Run ruff to check code style in the src and tests directories

      - name: Test
        run: pytest -q
        # Step 5: Run the tests using pytest in quiet mode
